# -*- coding: utf-8 -*-
"""Sampling_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E03-AlLda2flNpH113Nz6Dyp6HjQNCgF
"""

import pandas as pd

df = pd.read_csv('Creditcard_data.csv')
df.head()

df.shape
df.info()
df['Class'].value_counts()

from sklearn.utils import resample

df_majority = df[df.Class == 0]
df_minority = df[df.Class == 1]

df_majority_downsampled = resample(
    df_majority,
    replace=False,
    n_samples=len(df_minority),
    random_state=42
)

df_balanced = pd.concat([df_majority_downsampled, df_minority])

df_balanced['Class'].value_counts()

X = df_balanced.drop('Class', axis=1)
y = df_balanced['Class']

sample1 = df_balanced.sample(frac=0.8, random_state=1)

from sklearn.model_selection import train_test_split

X_train2, _, y_train2, _ = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=2
)

sample2 = pd.concat([X_train2, y_train2], axis=1)

step = 2
sample3 = df_balanced.iloc[::step]

sample4 = resample(
    df_balanced,
    replace=True,
    n_samples=len(df_balanced),
    random_state=4
)

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=5)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

models = {
    "M1_Logistic": LogisticRegression(max_iter=1000),
    "M2_DecisionTree": DecisionTreeClassifier(),
    "M3_RandomForest": RandomForestClassifier(),
    "M4_KNN": KNeighborsClassifier(),
    "M5_SVM": SVC()
}

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def evaluate(sample, model):
    X = sample.drop('Class', axis=1)
    y = sample['Class']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    return accuracy_score(y_test, y_pred) * 100

results = {}

samples = {
    "Sampling1": sample1,
    "Sampling2": sample2,
    "Sampling3": sample3,
    "Sampling4": sample4
}

for model_name, model in models.items():
    results[model_name] = {}
    for samp_name, samp in samples.items():
        acc = evaluate(samp, model)
        results[model_name][samp_name] = round(acc, 2)

results_df = pd.DataFrame(results).T
results_df

from sklearn.model_selection import cross_val_score

cv_results = {}

for model_name, model in models.items():
    scores = cross_val_score(model, X, y, cv=skf, scoring='accuracy')
    cv_results[model_name] = round(scores.mean() * 100, 2)

cv_results